package xyz.hedo.shop.controller.command;

public enum CommandName {
    DELETE_USER,
    VIEW_ALL_USERS,
    VIEW_USER_DETAILS,

    CREATE_CATEGORY,
    DELETE_CATEGORY,
    VIEW_ALL_CATEGORIES,
    VIEW_CATEGORY_DETAILS,

    CREATE_EQUIPMENT,
    DELETE_EQUIPMENT,
    VIEW_ALL_EQUIPMENTS,
    VIEW_EQUIPMENT_DETAILS,

    RENT_EQUIPMENT,
    RETURN_EQUIPMENT,

    VIEW_ALL_ORDERS,
    VIEW_ACTIVE_ORDERS,
    VIEW_EXPIRED_ORDERS,
    VIEW_ORDER_DETAILS,

    SIGN_UP,
    SIGN_IN,
    SIGN_OUT,

    WRONG_REQUEST,
}
